# Generated by Django 6.0.4 on 2026-04-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('Perdido', 'Perdido'), ('Encontrado', 'Encontrado'), ('Avistado', 'Avistado')])),
                ('nombre_mascota', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('tamano', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fech_perdida', models.DateField()),
                ('hora_perdida', models.TimeField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=300, null=True)),
                ('en_adopcion', models.BooleanField(default=False)),
                ('adoptado', models.BooleanField(default=False)),
                ('estado_reporte', models.CharField(choices=[('Activo', 'Activa'), ('Resuelto', 'Resuelto'), ('Inconcluso', 'Inconcluso')])),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_enable', models.BooleanField(default=False)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='mascotas_app.reporte')),
            ],
        ),
    ]
