# Generated by Django 6.0.4 on 2026-06-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='foto_url',
            new_name='foto_url_one',
        ),
        migrations.AddField(
            model_name='reporte',
            name='foto_url_two',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='foto_vector',
            field=models.JSONField(blank=True, help_text='Vector de características visuales generado por el microservicio IA (1280 dims).', null=True),
        ),
    ]
