# Generated by Django 6.0.4 on 2026-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas_app', '0002_rename_foto_url_reporte_foto_url_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
